server:
  port: 19997
spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
mybatis-plus:
  type-aliases-package: per.graphql.domain
  global-config:
    banner: false